---
# tasks file for roles/omero-web-apps

- name: omero web apps | install web-app
  become: yes
  pip:
    name: "{{ item }}"
    state: present
  with_items: "{{ omero_web_apps_packages }}"
  notify:
    - restart omero-web

- name: omero web apps | add application web configuration
  become: yes
  template:
    dest: "{{ omero_web_apps_omeroweb_config_dir }}/{{ omero_web_apps_config_name }}.omero"
    force: yes
    src: omero-web-apps-omero.j2
  notify:
    - restart omero-web
